# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AOLserver-CtrlPort
version:      0.01
version_from: lib/AOLserver/CtrlPort.pm
installdirs:  site
requires:
    Log::Log4perl:                 
    Net::Telnet:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
